services:
  - type: web
    name: pickme-backend
    env: java
    region: oregon # or singapore for Asia
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Xmx512m -Dserver.port=$PORT -jar target/PickMeApplication-1.0-SNAPSHOT.jar --spring.profiles.active=prod
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
